wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("<str:title>", views.title, name="title"),
    path("create/add", views.add, name="add"),
    path("<str:title>/edit", views.edit, name="edit"),
    path("<str:title>/change", views.change, name="change"),
    path("random/", views.rand, name="random")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
from os import path
from wiki.settings import BASE_DIR
from . import util
import random
import markdown2


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def title(request, title):
    return render(request, "encyclopedia/content.html", {"content": markdown2.markdown(util.get_entry(title)), "title": title})


def search(request):
    search = request.POST['q']
    lst = util.sub_query(str(search))
    if util.get_entry(search) is not None:
        return redirect(f'/{search}')
    elif len(lst) != 0:
        return render(request, "encyclopedia/index.html", {"entries": lst})
    else:
        return render(request, "encyclopedia/content.html", {"title": "Not Found"})


class NewPage(forms.Form):

    # class Meta:
    header = forms.CharField(label="New Header")
    body = forms.CharField(label="New Content",
                           widget=forms.Textarea(attrs={'rows': 3}))


class EditForm(forms.Form):
    # init to take parameters into the variable initial
    def __init__(self, *args, **kwargs):
        my_arg = kwargs.pop('my_arg', None)
        super(EditForm, self).__init__(*args, **kwargs)
        self.fields['my_field'].initial = my_arg

    my_field = forms.CharField(
        label="Edit", widget=forms.Textarea(attrs={"size": "80"}))


def create(request):
    return render(request, "encyclopedia/create.html", {"form": NewPage()})


def add(request):
    # boilerplate data validation
    if request.method == "POST":
        form = NewPage(request.POST)
        if form.is_valid():
            title = form.cleaned_data["header"]
            body = form.cleaned_data["body"]
            # this part takes care of the md file generation
            if util.get_entry(title.capitalize()) is None:
                file_path = path.join(
                    BASE_DIR, f'entries/{title.capitalize()}.md')
                with open(file_path, "w") as file:
                    file.write(f"# {title.capitalize()} \n \n")
                    file.write(body)
                # redirect to the new website if successful
                return redirect(f'/{title}')
            # duplicate finder
            else:
                return render(request, "encyclopedia/content.html", {"message": "Error: Duplicate found"})

        # re-renders the page if the input form is invalid
        else:
            return render(request, "encyclopedia/create.html", {'form': form})
    # if the request method is not post
    return render(request, "encyclopedia/create.html", {"form": NewPage()})


def edit(request, title):
    file_path = path.join(
        BASE_DIR, f'entries/{title.capitalize()}.md')
    with open(file_path, "r") as file:
        content = file.read()
        return render(request, "encyclopedia/edit.html", {'form': EditForm(my_arg=content), 'title': title})


# Someone finish the form validation please!
def change(request, title):
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            body = form.cleaned_data["my_field"]
            file_path = path.join(
                BASE_DIR, f'entries/{title}.md')
            with open(file_path, "w") as file:
                file.write(f"# {title.capitalize()} \n \n")
                file.write(body)
            return redirect(f'/{title}')


def rand(request):
    lst = util.list_entries()
    title = lst[random.randint(0, len(lst)-1)]
    return redirect(f'/{title}')

wiki/encyclopedia/templates/encyclopedia/add.html
{% extends 'encyclopedia/layout.html' %}

{% block body %}
    <form>  
    <table>
    {{form.as_table}}
    </table>
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/content.html
{% extends 'encyclopedia/layout.html' %}
        {%block body%}
                {% if content is not None %}
                        <span hidden>
                        <h1>{{ title }}</h1>
                        </span>
                        <p>{{ content|safe }}</p>
                        <form action = "{% url 'encyclopedia:edit' title=title%}" method = "post" >
                                {% csrf_token %}
                                <input type = "submit" value= "Edit">
                        </form>
                {% else %}
                        {% if message is None%}
                                <h1> Content is not found </h1>
                        {%else%}
                                <h1>{{message}}</h1>
                        {% endif %}
                {%endif%}
        {%endblock%}

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends 'encyclopedia/layout.html' %}

{% block body %}
    <form method = "POST" action = "{% url 'encyclopedia:add'%}"> 
        {% csrf_token %}
        <table>
        {{form.as_table}}
        </table>
    <input type = "submit">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}

    {% block body %}
    <h1>{{title}}</h1>
    <form method = "POST" action = "{% url 'encyclopedia:change' title=title %}"> 
        {% csrf_token %}
        {{form}}
    <input type = "submit" value = "save">
    </form>
    {% endblock body %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %} {% block title %} Encyclopedia 
{% endblock %} {% block body %}
<h1>All Pages</h1>

<ul>
    {% for entry in entries %}
    <li><a href= "{% url 'encyclopedia:title' title=entry %}"> {{entry}} </a></li> 
    {% endfor %}
</ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action = "{% url 'encyclopedia:search' %}" method = "POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href ="{% url 'encyclopedia:create'%}">
                    Create New Page </a>
                </div>
                <div>
                <a href = "{% url 'encyclopedia:random'%}">
                    Random Page
                </a>
                </div>
                {% block nav %} {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %} {% endblock %}
            </div>
        </div>
    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

    {% block search %}
        <form action = "{% url 'encyclopedia:search' %}" method = "post">
            {% csrf_token %}
            {{ form }}
            <input type = "submit">
        </form>
    {% endblock %}